remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:srimath8@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/SrimathM1"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hunterz-killer"
